version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
      - dependency-name: "@types/express"
      - dependency-name: "@types/node"
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "eslint-config-prettier"
      - dependency-name: "eslint-plugin-node"
      - dependency-name: "eslint-plugin-prettier"
      - dependency-name: "prettier"
      - dependency-name: "typescript"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "sdk-node"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "otelcol-auto-instrumentation"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "meta-package"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
